version: '3.8'
services:
  app-blue:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - VERSION=blue
    container_name: app-blue

  app-green:
    build: .
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - VERSION=green
    container_name: app-green

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-blue
      - app-green
    container_name: nginx-lb
